<a href="https://colab.research.google.com/github/labviros/computer-vision-topics/blob/version2020/lesson01-basics/basic_math_for_cv_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Mathematics for Computer Vision with Python - Part 2 - Matrices
In this notebook we will cover some  linear algebraic operations and properties of matrices.

##Libraries required
The main library used here is [Numpy](http://www.numpy.org/), wich is part of [Scipy](https://www.scipy.org/) "Python-based ecosystem of open-source software for mathematics, science, and engineering".

To begin with the codes, we use this common import:

In [ ]:
import numpy as np
import scipy



## Matrices
Two-dimensional arrays are referred to as matrices and, in computer vision, these play a significant role. An image in the digital world is represented as a matrix; hence, the operations that we will study here are applicable to images as well.

Matrix $\mathbf{\mathit{A}}$ is denoted as follows:
> \begin{bmatrix}
a_{11} & a_{12} & \cdots  & a_{1n} \\
a_{21} & a_{22} & \cdots  & a_{2n} \\
\vdots & \vdots  & \vdots  & \vdots \\
a_{m1} & a_{m2} & \cdots  & a_{mn} \\
\end{bmatrix}


Here, the shape of the matrix is $m \times n$ with $m$ rows and $n$ collumns. If $m=n$, the matrix is called a square matrix.
In Python, we can make a sample matrix, as follows:

In [ ]:
A = np.array([[1,1.2,3,0],[4,5,6,0],[7,8,92,1]])
print(A)

[[ 1.   1.2  3.   0. ]
 [ 4.   5.   6.   0. ]
 [ 7.   8.  92.   1. ]]


You can also access some properties of the matrix using the basic methods.

In [ ]:
print('Data type:', A.dtype)
print('Matrix size:', A.size)
print('Matrix shape:', A.shape)
print('Rows:', A.shape[0], ' Columns: ', A.shape[1])
print('Data: \n', A)



Data type: float64
Matrix size: 12
Matrix shape: (3, 4)
Rows: 3  Columns:  4
Data: 
 [[ 1.   1.2  3.   0. ]
 [ 4.   5.   6.   0. ]
 [ 7.   8.  92.   1. ]]


**Attention:** In Python the first index of a row or column of a matrix is represented as 0 (zero).

In order to select one element, one line or one column of the matrix, you can do as follows:

In [ ]:
print(A)
# Element from the second line and third column
a23 = A[1,2]
print("Element a23: ", a23)
# First line of the matrix
l = A[0,:]
print("First line: ", l)
# Third colunm
c = A[:,2]
print("Terceira coluna: ", c)
# Accessing a submatrix
s = A[0:2,1:3]
print("Submatrix:\n",s)
s = A[-2,0:-1]
print("Submatrix:\n",s)
s = A[-2,2:]
print("Submatrix:\n",s)


[[ 1.   1.2  3.   0. ]
 [ 4.   5.   6.   0. ]
 [ 7.   8.  92.   1. ]]
Element a23:  6.0
First line:  [1.  1.2 3.  0. ]
Terceira coluna:  [ 3.  6. 92.]
Submatrix:
 [[1.2 3. ]
 [5.  6. ]]
Submatrix:
 [4. 5. 6.]
Submatrix:
 [6. 0.]


## Operation on matrices
We will be performing similar operations on matrices as we did on vectors. The only difference will be in the way we perform these operations. To understand this in detail, go through the following sections.

### Addtion
In order to perform the addition of two matrices $\mathbf{\mathit{A}}$ and $\mathbf{\mathit{B}}$, both of them should be of the same shape. The addition operation is an element-wise addition done to create a matrix C of the same shape as $\mathbf{\mathit{A}}$ and $\mathbf{\mathit{B}}$.

>$C = A + B$

Here is an example:

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,1,1],[1,1,1],[1,1,1]])
C = A+B
print(A, '\n')
print(B, '\n')
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 1 1]
 [1 1 1]
 [1 1 1]] 

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### Subtraction
Similar to addition, subtracting matrix $\mathbf{\mathit{B}}$ from matrix $\mathbf{\mathit{A}}$ requires both of them to be of the same shape. The resulting matrix $\mathbf{\mathit{C}}$ will be of the same shape as $\mathbf{\mathit{A}}$ and $\mathbf{\mathit{B}}$.
> $C = A - B$

The following is an example of subtracting $\mathbf{\mathit{B}}$ from $\mathbf{\mathit{A}}$:

In [ ]:
A = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
B = np.array([[1,1,1], [1,1,1], [1,1,1]])
C = A - B
print(A, '\n')
print(B, '\n')
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 1 1]
 [1 1 1]
 [1 1 1]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Matrix multiplication by a scalar

In [ ]:
A = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

B = 5*A
print(A, '\n')
print(B, '\n')


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[ 5 10 15]
 [20 25 30]
 [35 40 45]] 



### Matrix multiplication
Consider two matrices: $\mathbf{\mathit{A}}$ with size $m \times  n$  and $\mathbf{\mathit{B}}$ with size $n \times p$. Now, the two matrices of sizes m x n and n x p are compatible for matrix multiplication, and will result on a matrix of size m x p.

The multiplication is given as follows:
> $C_{m \times p} =A_{m \times n} . B_{n \times p}$

Here, each element in $C$ is given as follows:
> $c_{i,j}=\sum_{k=1}^{n}a_{i,k}b_{k,j}$

Since matrix multiplication depends on the order of multiplication, reversing the order may result in a different matrix or an invalid multiplication due to size mismatch.

This is performed with Python, as follows:

In [ ]:
# A matrix of size (2x3)
A = np.array([[1,2,3],[4,5,6]])
# A matrix of size (3x2)
B = np.array([[1,0],[0,1],[1,0]])
C = np.dot(A,B) # size (2x2)

print(A, '\n')
print(B, '\n')
print(C, '\n')



[[1 2 3]
 [4 5 6]] 

[[1 0]
 [0 1]
 [1 0]] 

[[ 4  2]
 [10  5]] 



##Using np.matrix instead of np.array
Instead of using np.array you can also use np.matrix to define a matrix and perform some operations.

In [ ]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('1 0; 0 1; 1 0')
print(A)
print('Matrix shape:',A.shape, '\n')
print(B)
print('Matrix shape:',B.shape, '\n')



[[1 2 3]
 [4 5 6]]
Matrix shape: (2, 3) 

[[1 0]
 [0 1]
 [1 0]]
Matrix shape: (3, 2) 



###Addition

In [ ]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('1 1 1; 1 1 1')
C = A+B

print(A, '\n')
print(B, '\n')
print(C, '\n')

[[1 2 3]
 [4 5 6]] 

[[1 1 1]
 [1 1 1]] 

[[2 3 4]
 [5 6 7]] 



###Subtration

In [ ]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('1 1 1; 1 1 1')
C = A-B
print(A, '\n')
print(B, '\n')
print(C, '\n')

[[1 2 3]
 [4 5 6]] 

[[1 1 1]
 [1 1 1]] 

[[0 1 2]
 [3 4 5]] 



###Multiplication
Note the difference on using np.array and np.matrix for multiplying matrices.

In [ ]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('1 0; 0 1; 1 0')
C = A*B
# Also works with np.dot
D = np.dot(A,B)
print(A, '\n')
print(B, '\n')
print(C, '\n')
print(D)

[[1 2 3]
 [4 5 6]] 

[[1 0]
 [0 1]
 [1 0]] 

[[ 4  2]
 [10  5]] 

[[ 4  2]
 [10  5]]


We have seen the basic operations with matrices; now we will see some of their properties.

In [ ]:
v = np.array([1,2,3])
v1 = np.array([[1],[2],[3]])
print(v)
print(v1)

print(v[1])
print(v1[1])

[1 2 3]
[[1]
 [2]
 [3]]
2
[2]


#Interesting:
A*B also works even if one of the matrices is defined as np.array.

In [ ]:
A = np.matrix('1 2 3; 4 5 6')
B = np.array([[1, 1],[0, 1],[1, 2]])
print(A, '\n')
print(B, '\n')
C = A*B
print(C, '\n')
D = B*A
print(D, '\n')



[[1 2 3]
 [4 5 6]] 

[[1 1]
 [0 1]
 [1 2]] 

[[ 4  9]
 [10 21]] 

[[ 5  7  9]
 [ 4  5  6]
 [ 9 12 15]] 



## Matrix properties
There are a few properties that are used on matrices for executing mathematical operations. They are mentioned in detail in this section.

### Transpose
When we interchange columns and rows of a matrix with each other, the resulting matrix is called the transpose of the matrix and is denoted as $A^T$ from the original matrix $A$.
An example of this is as follows:

In [ ]:
# using np.array
A = np.array([[1, 2, 3],[4, 5, 6]])
print('Matrix A:')
print(A, '\n')
print('A_transpose:')
print(np.transpose(A), '\n')
# A simpler way
print(A.T,'\n')

#using np.matrix
B = np.matrix ('1 2 3; 4 5 6')
print('Matrix B:')
print(B, '\n')
print('B_transpose:')
print(np.transpose(B),'\n')
# A simpler way
print(B.T)

Matrix A:
[[1 2 3]
 [4 5 6]] 

A_transpose:
[[1 4]
 [2 5]
 [3 6]] 

[[1 4]
 [2 5]
 [3 6]] 

Matrix B:
[[1 2 3]
 [4 5 6]] 

B_transpose:
[[1 4]
 [2 5]
 [3 6]] 

[[1 4]
 [2 5]
 [3 6]]


### Identity matrix
This is a special kind of matrix with diagonal elements as $1$ and all other elements as zero:

In [ ]:
I = np.identity(3) #size of identity matrix
print(I,'\n')
I = np.identity(6) #size of identity, matrix
print(I,'\n')

# Another way
I = np.eye(5)
print(I,'\n')

# Attention
# If we use 2 parameters we get a matrix that is not square
I = np.eye(5,7)
print(I)

I = np.eye(7,5)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


An interesting property of the identity matrix is that it doesn't modify the target matrix after multiplication, that is
> $C=A$.$I$

> or

> $C=I$.$A$

will result in

> $C = A$


### Zero matrix
Some times we need to initialize a matrix with zeros. You can do as:

In [ ]:
A = np.zeros((5,3))
print(A,'\n')

B = np.zeros(5)
print(B)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[0. 0. 0. 0. 0.]


### Diagonal matrix
Extending the definition of an identity matrix, in a diagonal matrix, the elements of a matrix along the main diagonal are non-zero and the rest of the values are zero. An example is as follows:

In [ ]:
A = np.array([[12,0,0],[0,50,0],[0,0,43]])
print(A)

B = np.diag((12,50,43))
print(B)


[[12  0  0]
 [ 0 50  0]
 [ 0  0 43]]
[[12  0  0]
 [ 0 50  0]
 [ 0  0 43]]


### Symetric matrix
In a symmetric matrix, the elements follow the property:
> $a_{i,j}=a_{j,i}$

This property, for a given symmetric matrix $A$, can also be defined in terms of its transpose as $A^T=A$

Let's consider an asymmetric $M$ square matrix (with size $n \times n$ ) given as follows:

In [ ]:
M = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


You can compute it's transpose as follows

In [ ]:
M_T = np.transpose(M)
print(M_T)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


We can show that  $M+M^T$ is a symetric matrix:

In [ ]:
print(M + M_T)

[[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]


It can be seen that the elements $m_{i,j}=m_{j,i}$.


### Skew-symmetric Matrix

In a skew-symmetric matrix, the elements follow the property:
> $a_{i,j}=-a_{j,i}$

while the elements of the diagonal are all zero.

> $A = \begin{bmatrix}
0 & -a_{12} &  a_{13} \\
a_{12} &0 &  -a_{23} \\
-a_{13} & a_{23} &  0 \\
\end{bmatrix}$

For a given skew-symmetric matrix $A$, its transpose can be defined as $A^T= -A$.

Following the examples above that used an asymetric $M$ square matrix, we can also compute a skew matrix as $M-M^T$, where each element:

In [ ]:
print(M - M_T)

[[ 0 -2 -4]
 [ 2  0 -2]
 [ 4  2  0]]


An important property arises from this. We can break any square matrix into a summation of a symmetric and a skew  matrix, as follows:
> $M = 0.5 \times \left ( M + M^T \right)+ 0.5 \times \left(M - M^T \right)$

The corresponding Python script to do that is:


In [ ]:
print(M,'\n')
symm = M + M_T
skew_symm = M - M_T
print(0.5*symm + 0.5*skew_symm)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Trace of a matrix
The trace of a matrix is the sum of all its diagonal elements:

In [ ]:
# using np.array
A = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print('Matrix: \n', A)
print('Trace: ', np.trace(A),'\n')

#using np.matrix
A = np.matrix('1 2 3; 4 5 6; 7 8 9')
print('Matrix: \n', A)
print('Trace: ', np.trace(A),'\n')


Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Trace:  15 

Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Trace:  15 



### Determinant
Geometrically, it can be viewed as the volume scaling factor of the linear transformation described by the matrix. Or its absolute value can also be considered as the volume enclosed by taking each row of the natrix as a vector. This can be computed, as follows:

In [ ]:
A = np.array([[2, 3],[ 5, 6]])
print('Matrix: \n', A)
print('Determinant: ', np.linalg.det(A))

Matrix: 
 [[2 3]
 [5 6]]
Determinant:  -2.9999999999999982


### Norm of a matrix
Continuing the norm formulation from the notebook on vectors, in a matrix, the most common type of norm is the Frobenius norm:
> $\left \|  A \right \|= \sqrt{\left({\sum_{i}\sum_{j}a^2_{i,j}} \right )}=\sqrt{tr \left(A^TA \right )}$

In Python we compute this way:

In [ ]:
A = np.matrix([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print('Matrix: \n', A)
print('Norm: ', np.linalg.norm(A),'\n')

# Checking...
R = np.transpose(A)*A
n = np.sqrt(np.trace(R))
print('Matrix: \n', A)
print('Norm: ', n)

Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Norm:  16.881943016134134 

Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Norm:  16.881943016134134


### Getting the inverse of a square matrix
The inverse of a matrix is usually denoted as $A^{-1}$, and has the following property:
> $AA^{-1} = I = A^{-1}A$

The inverse is unique for each matrix; however, not all matrices have inverse matrices. An example of the inverse of a matrix can be seen below:

In [ ]:
A = np.array([[1, 2, 3],[5, 4, 6], [9, 8, 7]])
A_inv = np.linalg.inv(A)
print(A_inv)

[[-6.66666667e-01  3.33333333e-01  4.93432455e-17]
 [ 6.33333333e-01 -6.66666667e-01  3.00000000e-01]
 [ 1.33333333e-01  3.33333333e-01 -2.00000000e-01]]


So, if we ge the product of $A$ and $A^{-1}$, we get the following result

In [ ]:
np.dot(A,A_inv)

array([[ 1.00000000e+00,  1.66533454e-16, -5.55111512e-17],
       [ 3.33066907e-16,  1.00000000e+00,  1.11022302e-16],
       [ 8.32667268e-16, -2.77555756e-16,  1.00000000e+00]])

We can see that the diagonal elements are *1* and all others are approximately *0*.

### Orthogonality
Another property associated with a square matrix is orthogonality.


If:
> $A^TA=I$

and
> $AA^T=I$

This also leads to
> $A^T=A^{-1}$

This is what happens with a rotation matrix, where $R^T=R^{-1}$ and $det(R) = +1$.



In [ ]:
ang = np.pi/7
c_ang = np.cos(ang)
s_ang = np.sin(ang)

R = np.matrix([[c_ang, -s_ang,0 ],[s_ang, c_ang, 0],[0,0,1]])
print (R, '\n')
print (np.transpose(R),'\n')
print (np.linalg.inv(R),'\n')
print(np.dot(R,R.T))


[[ 0.90096887 -0.43388374  0.        ]
 [ 0.43388374  0.90096887  0.        ]
 [ 0.          0.          1.        ]] 

[[ 0.90096887  0.43388374  0.        ]
 [-0.43388374  0.90096887  0.        ]
 [ 0.          0.          1.        ]] 

[[ 0.90096887  0.43388374  0.        ]
 [-0.43388374  0.90096887  0.        ]
 [ 0.          0.          1.        ]] 

[[ 1.00000000e+00 -1.10451148e-17  0.00000000e+00]
 [-1.10451148e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


### Computing eigenvalues and eigenvectors
The eigenvalue $\lambda$ of a square matrix $A$ has the property such that any transformation on $A$ with the corresponding eigenvector $x$ is equal to the scalar multiplication of $\lambda$ by $x$:
> $Ax=\lambda x$

where
> $x \neq 0$

To compute eigenvalues and eigenvectors of $A$, we need to solve the characteristic equation, as follows:

> $\left | \lambda I-A \right |=0$

Here, $I$ is an identity martix of the same size as $A$.

We can do this using Numpy as follows:

In [ ]:
A = np.array([[1, 2, 3],[5, 4, 6], [9, 8, 7]])
eigvals, eigvectors = np.linalg.eig(A)
print("Eigen Values: ", eigvals,'\n')
print("Eigen Vectors:\n", eigvectors)

Eigen Values:  [15.16397149 -2.30607508 -0.85789641] 

Eigen Vectors:
 [[-0.24668682 -0.50330679  0.54359359]
 [-0.5421775  -0.3518559  -0.8137192 ]
 [-0.80323668  0.78922728  0.20583261]]


### Singular Value Decomposition
Singular Value Decomposition (SVD) is used to perform decomposition of a matrix $A$ into:
>> $A = U\Sigma V^{T}$

where $U$ and $V^{T}$ are orthogonal matrices and $\Sigma$ is a diagonal matrix:


In [ ]:
A = np.array([[10, 2, 3],[5, 43, 6], [93, 8, 71]])
print(A)

U, s, Vt = np.linalg.svd(A, full_matrices=True)
print('Matrix U:\n',U, '\n')
print(np.linalg.det(U),'\n')
print('Diagonal values s: ',s, '\n')
print('Matrix Vt: \n',Vt,'\n')
print(np.linalg.det(Vt),'\n')

S = np.diag(s)

print(S,'\n')

A1 = np.dot(U,np.dot(S,Vt))

print(A1,'\n')


[[10  2  3]
 [ 5 43  6]
 [93  8 71]]
Matrix U:
 [[-0.08398156 -0.01920565 -0.99628221]
 [-0.10248995 -0.99434528  0.0278077 ]
 [-0.99118258  0.10444425  0.08153828]] 

1.0 

Diagonal values s:  [118.23663388  42.22857206   3.72103608] 

Matrix Vt: 
 [[-0.79105978 -0.10575818 -0.6025277 ]
 [ 0.10773588 -0.99363304  0.03295999]
 [-0.60217722 -0.03884053  0.79741708]] 

0.9999999999999998 

[[118.23663388   0.           0.        ]
 [  0.          42.22857206   0.        ]
 [  0.           0.           3.72103608]] 

[[10.  2.  3.]
 [ 5. 43.  6.]
 [93.  8. 71.]] 

